version: '3.8'

services:
  web:
    build: ./app
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.example
    volumes:
      - ./app:/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db


volumes:
  postgres_data: